- name: Conditional Example
  hosts: servers
  become: yes

  tasks:
   - name: Install Apache on Ubuntu
     apt:
      name: apache2
      state: present
     when: ansible_facts['distribution'] == "Ubuntu"
