---
- name: Show Secret
  hosts: servers
  become: yes
  
  vars_files:
    - pass.yml

  tasks:
   - name: Show Password
     debug:
       msg: "My password is {{ password }}"
     no_log: true

   - name: Show Api Key
     debug:
       msg: "My API Key is {{ api_key }}"
     no_log: true  
