#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/docker
#
- name: Update system
  apt:
    name: "*"
    state: present

- name: Install Docker  
  apt:
    name: docker.io
    state: latest

- name: Add users to docker group
  user:
    name: "{{ item }}"
    group: docker
    append: true
    loop: "{{ docker_user }}"

- name: Restart Docker
  service:
    name: docker
    state: restarted

- name: Show docker version
  command: docker --version
  
